# .travis.yml

jobs:
  include:
    - dist: bionic
      php: 7.4
    - dist: xenial
      php: 8.1

os: linux

arch: arm64

language: php

services:
  - rabbitmq

addons:
  apt:
    packages:
    - rabbitmq-server

cache:
  directories:
    - vendor

before_script:
  - composer install --no-interaction
  - pecl install pcov

script:
  - vendor/bin/phpunit
  - vendor/bin/tlint
  - vendor/bin/php-formatter fix -v --dry-run
