# .travis.yml
language: php

jobs:
  include:
    - php: 7.4
    - php: 8.0
    - php: 8.1
    - php: 8.3

services:
  - rabbitmq

addons:
  apt:
    packages:
    - rabbitmq-server

cache:
  directories:
    - vendor

before_script:
  - composer install --no-interaction
  - pecl install pcov

script:
  - vendor/bin/phpunit
  - vendor/bin/tlint
  - vendor/bin/php-formatter fix -v --dry-run
