# .travis.yml
language: php

jobs:
  include:
    - php: 7.4
      dist: xenial
    - php: 8.0
      dist: focal
    - php: 8.1
      dist: focal
    - php: 8.3
      dist: focal

services:
  - rabbitmq

addons:
  apt:
    packages:
    - rabbitmq-server

cache:
  directories:
    - vendor

before_script:
  - composer install --no-interaction
  - pecl install pcov

script:
  - vendor/bin/phpunit
  - vendor/bin/tlint
  - vendor/bin/php-formatter fix -v --dry-run
