# .travis.yml
dist: xenial

os: linux

arch: arm64

language: php

sudo: required

php:
  - 8.1

services:
  - rabbitmq

addons:
  apt:
    packages:
    - rabbitmq-server

cache:
  directories:
    - vendor

before_script:
  - composer self-update
  - composer install --no-interaction
  - pecl install pcov

script:
  - vendor/bin/phpunit
  - vendor/bin/tlint