# .travis.yml
dist: xenial

os: linux

arch: arm64

language: php

sudo: required

php:
  - 7.4

services:
  - mysql
  - rabbitmq

addons:
  apt:
    packages:
    - rabbitmq-server

cache:
  directories:
    - vendor

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/tlint